[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/muslim/quran/data/*.gz"
  [headers.values]
   Content-Type= "application/json"
   Content-Encoding= "gzip"
   cache-control = ''' max-age=31536000, immutable '''

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
