[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Header untuk semua file kecuali yang lebih spesifik
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Cache-Control = "max-age=31536000, immutable"

# Header khusus untuk file yang dikompresi
[[headers]]
  for = "/muslim/quran/data/*.gz"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public, max-age=0, must-revalidate"
