const BOOKMARK_KEY = "BOOKMARK";
const LASTREAD_KEY = "LASTREAD";
const LASTREADSURAH_KEY = "LASTREADSURAH";
const LASTVISITPAGE_KEY = "LAST_VISIT_PAGE";
const FAVORITESURAH_KEY = "FAVORITESURAH";
const PLANREAD_KEY = "PLANREAD";
const SETTING_PREFS_KEY = "SETTING_PREFS_KEY";

export {
  BOOKMARK_KEY,
  FAVORITESURAH_KEY,
  LASTREAD_KEY,
  LASTREADSURAH_KEY,
  LASTVISITPAGE_KEY,
  PLANREAD_KEY,
  SETTING_PREFS_KEY,
};
